name: CMake Build with vcpkg

on:
  push:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            preset: linux64
          - os: windows-latest
            preset: win64
      fail-fast: false
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: ⚙️ Install deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get -y install libltdl-dev nasm

      # Install latest CMake and Ninja.
      - uses: lukka/get-cmake@latest
      # Or pin to a specific CMake version:
      # lukka/get-cmake@v3.27

      - name: Setup anew (or from cache) vcpkg (and does not build any package)
        uses: lukka/run-vcpkg@v11 # Always specify the specific _version_ of the
                                  # action you need, `v11` in this case to stay up
                                  # to date with fixes on the v11 branch.


      - name: Run CMake consuming CMakePreset.json and run vcpkg to build packages
        uses: lukka/run-cmake@v10
        with:
          configurePreset: '${{ matrix.preset }}'
          buildPreset: '${{ matrix.preset }}'
          packagePreset: '${{ matrix.preset }}-zip'
      
      # Publish ZIP archive as artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: RTS-${{ matrix.os }}.zip
          path: |
            build/default/RTS-*.zip
